apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  MINIO_ACCESS_KEY: bWluaW8=
  MINIO_SECRET_KEY: bWluaW8xMjM=